name: ctt test

on:
  issues:
    types: [opened, edited, reopened]
  
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: check fill
        uses: ./
        with:
          path: './.github/workflows/'
          token: ${{ secrets.GITHUB_TOKEN }}
