name: ctt test

on:
  issues:
    types: [opened, edited, reopened]
  
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: check
        uses: ./
        with:
          path: './.github/workflows/'
          file: 'main2.yml'
          token: ${{ secrets.GITHUB_TOKEN }}
      - run: |
          echo "name: ${{ steps.check.outputs.name }}"
