name: ctt test hahaha

on:
  issues:
    types: [reopened]
  
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@lastest
      - name: check fill
        uses: actions/cache@lastest
      - uses: actions/stale@v6.0.1
      - uses: actions/setup-go@v3
     
